/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// Filters Schema for the Filters endpoint.
type Filters struct {
	// Additional Information provided by OUP
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Results *FiltersResults `json:"results,omitempty"`
}

// NewFilters instantiates a new Filters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilters() *Filters {
	this := Filters{}
	return &this
}

// NewFiltersWithDefaults instantiates a new Filters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiltersWithDefaults() *Filters {
	this := Filters{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Filters) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Filters) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Filters) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Filters) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *Filters) GetResults() FiltersResults {
	if o == nil || o.Results == nil {
		var ret FiltersResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Filters) GetResultsOk() (*FiltersResults, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *Filters) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given FiltersResults and assigns it to the Results field.
func (o *Filters) SetResults(v FiltersResults) {
	o.Results = &v
}

func (o Filters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableFilters struct {
	value *Filters
	isSet bool
}

func (v NullableFilters) Get() *Filters {
	return v.value
}

func (v *NullableFilters) Set(val *Filters) {
	v.value = val
	v.isSet = true
}

func (v NullableFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilters(val *Filters) *NullableFilters {
	return &NullableFilters{value: val, isSet: true}
}

func (v NullableFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


