/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// BilingualSenseConstructions struct for BilingualSenseConstructions
type BilingualSenseConstructions struct {
	Domains *DomainsList `json:"domains,omitempty"`
	Examples *[][]string `json:"examples,omitempty"`
	// various types of notes that appear
	Notes *[]map[string]interface{} `json:"notes,omitempty"`
	Regions *RegionsList `json:"regions,omitempty"`
	Registers *RegistersList `json:"registers,omitempty"`
	// The construction text
	Text string `json:"text"`
	// A list of written or spoken rendering of the meaning of a word or text in another language(s)
	Translations *[]map[string]interface{} `json:"translations,omitempty"`
}

// NewBilingualSenseConstructions instantiates a new BilingualSenseConstructions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBilingualSenseConstructions(text string) *BilingualSenseConstructions {
	this := BilingualSenseConstructions{}
	this.Text = text
	return &this
}

// NewBilingualSenseConstructionsWithDefaults instantiates a new BilingualSenseConstructions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBilingualSenseConstructionsWithDefaults() *BilingualSenseConstructions {
	this := BilingualSenseConstructions{}
	return &this
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *BilingualSenseConstructions) GetDomains() DomainsList {
	if o == nil || o.Domains == nil {
		var ret DomainsList
		return ret
	}
	return *o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetDomainsOk() (*DomainsList, bool) {
	if o == nil || o.Domains == nil {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *BilingualSenseConstructions) HasDomains() bool {
	if o != nil && o.Domains != nil {
		return true
	}

	return false
}

// SetDomains gets a reference to the given DomainsList and assigns it to the Domains field.
func (o *BilingualSenseConstructions) SetDomains(v DomainsList) {
	o.Domains = &v
}

// GetExamples returns the Examples field value if set, zero value otherwise.
func (o *BilingualSenseConstructions) GetExamples() [][]string {
	if o == nil || o.Examples == nil {
		var ret [][]string
		return ret
	}
	return *o.Examples
}

// GetExamplesOk returns a tuple with the Examples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetExamplesOk() (*[][]string, bool) {
	if o == nil || o.Examples == nil {
		return nil, false
	}
	return o.Examples, true
}

// HasExamples returns a boolean if a field has been set.
func (o *BilingualSenseConstructions) HasExamples() bool {
	if o != nil && o.Examples != nil {
		return true
	}

	return false
}

// SetExamples gets a reference to the given [][]string and assigns it to the Examples field.
func (o *BilingualSenseConstructions) SetExamples(v [][]string) {
	o.Examples = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *BilingualSenseConstructions) GetNotes() []map[string]interface{} {
	if o == nil || o.Notes == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetNotesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Notes == nil {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *BilingualSenseConstructions) HasNotes() bool {
	if o != nil && o.Notes != nil {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []map[string]interface{} and assigns it to the Notes field.
func (o *BilingualSenseConstructions) SetNotes(v []map[string]interface{}) {
	o.Notes = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *BilingualSenseConstructions) GetRegions() RegionsList {
	if o == nil || o.Regions == nil {
		var ret RegionsList
		return ret
	}
	return *o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetRegionsOk() (*RegionsList, bool) {
	if o == nil || o.Regions == nil {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *BilingualSenseConstructions) HasRegions() bool {
	if o != nil && o.Regions != nil {
		return true
	}

	return false
}

// SetRegions gets a reference to the given RegionsList and assigns it to the Regions field.
func (o *BilingualSenseConstructions) SetRegions(v RegionsList) {
	o.Regions = &v
}

// GetRegisters returns the Registers field value if set, zero value otherwise.
func (o *BilingualSenseConstructions) GetRegisters() RegistersList {
	if o == nil || o.Registers == nil {
		var ret RegistersList
		return ret
	}
	return *o.Registers
}

// GetRegistersOk returns a tuple with the Registers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetRegistersOk() (*RegistersList, bool) {
	if o == nil || o.Registers == nil {
		return nil, false
	}
	return o.Registers, true
}

// HasRegisters returns a boolean if a field has been set.
func (o *BilingualSenseConstructions) HasRegisters() bool {
	if o != nil && o.Registers != nil {
		return true
	}

	return false
}

// SetRegisters gets a reference to the given RegistersList and assigns it to the Registers field.
func (o *BilingualSenseConstructions) SetRegisters(v RegistersList) {
	o.Registers = &v
}

// GetText returns the Text field value
func (o *BilingualSenseConstructions) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetTextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *BilingualSenseConstructions) SetText(v string) {
	o.Text = v
}

// GetTranslations returns the Translations field value if set, zero value otherwise.
func (o *BilingualSenseConstructions) GetTranslations() []map[string]interface{} {
	if o == nil || o.Translations == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Translations
}

// GetTranslationsOk returns a tuple with the Translations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BilingualSenseConstructions) GetTranslationsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Translations == nil {
		return nil, false
	}
	return o.Translations, true
}

// HasTranslations returns a boolean if a field has been set.
func (o *BilingualSenseConstructions) HasTranslations() bool {
	if o != nil && o.Translations != nil {
		return true
	}

	return false
}

// SetTranslations gets a reference to the given []map[string]interface{} and assigns it to the Translations field.
func (o *BilingualSenseConstructions) SetTranslations(v []map[string]interface{}) {
	o.Translations = &v
}

func (o BilingualSenseConstructions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Domains != nil {
		toSerialize["domains"] = o.Domains
	}
	if o.Examples != nil {
		toSerialize["examples"] = o.Examples
	}
	if o.Notes != nil {
		toSerialize["notes"] = o.Notes
	}
	if o.Regions != nil {
		toSerialize["regions"] = o.Regions
	}
	if o.Registers != nil {
		toSerialize["registers"] = o.Registers
	}
	if true {
		toSerialize["text"] = o.Text
	}
	if o.Translations != nil {
		toSerialize["translations"] = o.Translations
	}
	return json.Marshal(toSerialize)
}

type NullableBilingualSenseConstructions struct {
	value *BilingualSenseConstructions
	isSet bool
}

func (v NullableBilingualSenseConstructions) Get() *BilingualSenseConstructions {
	return v.value
}

func (v *NullableBilingualSenseConstructions) Set(val *BilingualSenseConstructions) {
	v.value = val
	v.isSet = true
}

func (v NullableBilingualSenseConstructions) IsSet() bool {
	return v.isSet
}

func (v *NullableBilingualSenseConstructions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBilingualSenseConstructions(val *BilingualSenseConstructions) *NullableBilingualSenseConstructions {
	return &NullableBilingualSenseConstructions{value: val, isSet: true}
}

func (v NullableBilingualSenseConstructions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBilingualSenseConstructions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


