/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// Entry struct for Entry
type Entry struct {
	CrossReferenceMarkers *[]string `json:"crossReferenceMarkers,omitempty"`
	// A reference to another word that is closely related, might provide additional information about the subject, has a variant spelling or is an abbreviated form of it.
	CrossReferences *[]map[string]interface{} `json:"crossReferences,omitempty"`
	Etymologies *[]string `json:"etymologies,omitempty"`
	// The different forms are correlated with meanings or functions which we text as 'features'
	GrammaticalFeatures *[]map[string]interface{} `json:"grammaticalFeatures,omitempty"`
	// Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
	HomographNumber *string `json:"homographNumber,omitempty"`
	// A list of inflected forms for an Entry.
	Inflections *[]InflectedForm `json:"inflections,omitempty"`
	// various types of notes that appear
	Notes *[]map[string]interface{} `json:"notes,omitempty"`
	// A list of possible pronunciations of a word
	Pronunciations *[]map[string]interface{} `json:"pronunciations,omitempty"`
	// Complete list of senses
	Senses *[]Sense `json:"senses,omitempty"`
	// Various words that are used interchangeably depending on the context, e.g 'aluminium' and 'aluminum'
	VariantForms *[]map[string]interface{} `json:"variantForms,omitempty"`
}

// NewEntry instantiates a new Entry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntry() *Entry {
	this := Entry{}
	return &this
}

// NewEntryWithDefaults instantiates a new Entry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntryWithDefaults() *Entry {
	this := Entry{}
	return &this
}

// GetCrossReferenceMarkers returns the CrossReferenceMarkers field value if set, zero value otherwise.
func (o *Entry) GetCrossReferenceMarkers() []string {
	if o == nil || o.CrossReferenceMarkers == nil {
		var ret []string
		return ret
	}
	return *o.CrossReferenceMarkers
}

// GetCrossReferenceMarkersOk returns a tuple with the CrossReferenceMarkers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetCrossReferenceMarkersOk() (*[]string, bool) {
	if o == nil || o.CrossReferenceMarkers == nil {
		return nil, false
	}
	return o.CrossReferenceMarkers, true
}

// HasCrossReferenceMarkers returns a boolean if a field has been set.
func (o *Entry) HasCrossReferenceMarkers() bool {
	if o != nil && o.CrossReferenceMarkers != nil {
		return true
	}

	return false
}

// SetCrossReferenceMarkers gets a reference to the given []string and assigns it to the CrossReferenceMarkers field.
func (o *Entry) SetCrossReferenceMarkers(v []string) {
	o.CrossReferenceMarkers = &v
}

// GetCrossReferences returns the CrossReferences field value if set, zero value otherwise.
func (o *Entry) GetCrossReferences() []map[string]interface{} {
	if o == nil || o.CrossReferences == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.CrossReferences
}

// GetCrossReferencesOk returns a tuple with the CrossReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetCrossReferencesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.CrossReferences == nil {
		return nil, false
	}
	return o.CrossReferences, true
}

// HasCrossReferences returns a boolean if a field has been set.
func (o *Entry) HasCrossReferences() bool {
	if o != nil && o.CrossReferences != nil {
		return true
	}

	return false
}

// SetCrossReferences gets a reference to the given []map[string]interface{} and assigns it to the CrossReferences field.
func (o *Entry) SetCrossReferences(v []map[string]interface{}) {
	o.CrossReferences = &v
}

// GetEtymologies returns the Etymologies field value if set, zero value otherwise.
func (o *Entry) GetEtymologies() []string {
	if o == nil || o.Etymologies == nil {
		var ret []string
		return ret
	}
	return *o.Etymologies
}

// GetEtymologiesOk returns a tuple with the Etymologies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetEtymologiesOk() (*[]string, bool) {
	if o == nil || o.Etymologies == nil {
		return nil, false
	}
	return o.Etymologies, true
}

// HasEtymologies returns a boolean if a field has been set.
func (o *Entry) HasEtymologies() bool {
	if o != nil && o.Etymologies != nil {
		return true
	}

	return false
}

// SetEtymologies gets a reference to the given []string and assigns it to the Etymologies field.
func (o *Entry) SetEtymologies(v []string) {
	o.Etymologies = &v
}

// GetGrammaticalFeatures returns the GrammaticalFeatures field value if set, zero value otherwise.
func (o *Entry) GetGrammaticalFeatures() []map[string]interface{} {
	if o == nil || o.GrammaticalFeatures == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.GrammaticalFeatures
}

// GetGrammaticalFeaturesOk returns a tuple with the GrammaticalFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetGrammaticalFeaturesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.GrammaticalFeatures == nil {
		return nil, false
	}
	return o.GrammaticalFeatures, true
}

// HasGrammaticalFeatures returns a boolean if a field has been set.
func (o *Entry) HasGrammaticalFeatures() bool {
	if o != nil && o.GrammaticalFeatures != nil {
		return true
	}

	return false
}

// SetGrammaticalFeatures gets a reference to the given []map[string]interface{} and assigns it to the GrammaticalFeatures field.
func (o *Entry) SetGrammaticalFeatures(v []map[string]interface{}) {
	o.GrammaticalFeatures = &v
}

// GetHomographNumber returns the HomographNumber field value if set, zero value otherwise.
func (o *Entry) GetHomographNumber() string {
	if o == nil || o.HomographNumber == nil {
		var ret string
		return ret
	}
	return *o.HomographNumber
}

// GetHomographNumberOk returns a tuple with the HomographNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetHomographNumberOk() (*string, bool) {
	if o == nil || o.HomographNumber == nil {
		return nil, false
	}
	return o.HomographNumber, true
}

// HasHomographNumber returns a boolean if a field has been set.
func (o *Entry) HasHomographNumber() bool {
	if o != nil && o.HomographNumber != nil {
		return true
	}

	return false
}

// SetHomographNumber gets a reference to the given string and assigns it to the HomographNumber field.
func (o *Entry) SetHomographNumber(v string) {
	o.HomographNumber = &v
}

// GetInflections returns the Inflections field value if set, zero value otherwise.
func (o *Entry) GetInflections() []InflectedForm {
	if o == nil || o.Inflections == nil {
		var ret []InflectedForm
		return ret
	}
	return *o.Inflections
}

// GetInflectionsOk returns a tuple with the Inflections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetInflectionsOk() (*[]InflectedForm, bool) {
	if o == nil || o.Inflections == nil {
		return nil, false
	}
	return o.Inflections, true
}

// HasInflections returns a boolean if a field has been set.
func (o *Entry) HasInflections() bool {
	if o != nil && o.Inflections != nil {
		return true
	}

	return false
}

// SetInflections gets a reference to the given []InflectedForm and assigns it to the Inflections field.
func (o *Entry) SetInflections(v []InflectedForm) {
	o.Inflections = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Entry) GetNotes() []map[string]interface{} {
	if o == nil || o.Notes == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetNotesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Notes == nil {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Entry) HasNotes() bool {
	if o != nil && o.Notes != nil {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []map[string]interface{} and assigns it to the Notes field.
func (o *Entry) SetNotes(v []map[string]interface{}) {
	o.Notes = &v
}

// GetPronunciations returns the Pronunciations field value if set, zero value otherwise.
func (o *Entry) GetPronunciations() []map[string]interface{} {
	if o == nil || o.Pronunciations == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Pronunciations
}

// GetPronunciationsOk returns a tuple with the Pronunciations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetPronunciationsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Pronunciations == nil {
		return nil, false
	}
	return o.Pronunciations, true
}

// HasPronunciations returns a boolean if a field has been set.
func (o *Entry) HasPronunciations() bool {
	if o != nil && o.Pronunciations != nil {
		return true
	}

	return false
}

// SetPronunciations gets a reference to the given []map[string]interface{} and assigns it to the Pronunciations field.
func (o *Entry) SetPronunciations(v []map[string]interface{}) {
	o.Pronunciations = &v
}

// GetSenses returns the Senses field value if set, zero value otherwise.
func (o *Entry) GetSenses() []Sense {
	if o == nil || o.Senses == nil {
		var ret []Sense
		return ret
	}
	return *o.Senses
}

// GetSensesOk returns a tuple with the Senses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetSensesOk() (*[]Sense, bool) {
	if o == nil || o.Senses == nil {
		return nil, false
	}
	return o.Senses, true
}

// HasSenses returns a boolean if a field has been set.
func (o *Entry) HasSenses() bool {
	if o != nil && o.Senses != nil {
		return true
	}

	return false
}

// SetSenses gets a reference to the given []Sense and assigns it to the Senses field.
func (o *Entry) SetSenses(v []Sense) {
	o.Senses = &v
}

// GetVariantForms returns the VariantForms field value if set, zero value otherwise.
func (o *Entry) GetVariantForms() []map[string]interface{} {
	if o == nil || o.VariantForms == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.VariantForms
}

// GetVariantFormsOk returns a tuple with the VariantForms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entry) GetVariantFormsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.VariantForms == nil {
		return nil, false
	}
	return o.VariantForms, true
}

// HasVariantForms returns a boolean if a field has been set.
func (o *Entry) HasVariantForms() bool {
	if o != nil && o.VariantForms != nil {
		return true
	}

	return false
}

// SetVariantForms gets a reference to the given []map[string]interface{} and assigns it to the VariantForms field.
func (o *Entry) SetVariantForms(v []map[string]interface{}) {
	o.VariantForms = &v
}

func (o Entry) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CrossReferenceMarkers != nil {
		toSerialize["crossReferenceMarkers"] = o.CrossReferenceMarkers
	}
	if o.CrossReferences != nil {
		toSerialize["crossReferences"] = o.CrossReferences
	}
	if o.Etymologies != nil {
		toSerialize["etymologies"] = o.Etymologies
	}
	if o.GrammaticalFeatures != nil {
		toSerialize["grammaticalFeatures"] = o.GrammaticalFeatures
	}
	if o.HomographNumber != nil {
		toSerialize["homographNumber"] = o.HomographNumber
	}
	if o.Inflections != nil {
		toSerialize["inflections"] = o.Inflections
	}
	if o.Notes != nil {
		toSerialize["notes"] = o.Notes
	}
	if o.Pronunciations != nil {
		toSerialize["pronunciations"] = o.Pronunciations
	}
	if o.Senses != nil {
		toSerialize["senses"] = o.Senses
	}
	if o.VariantForms != nil {
		toSerialize["variantForms"] = o.VariantForms
	}
	return json.Marshal(toSerialize)
}

type NullableEntry struct {
	value *Entry
	isSet bool
}

func (v NullableEntry) Get() *Entry {
	return v.value
}

func (v *NullableEntry) Set(val *Entry) {
	v.value = val
	v.isSet = true
}

func (v NullableEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntry(val *Entry) *NullableEntry {
	return &NullableEntry{value: val, isSet: true}
}

func (v NullableEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


