/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// HeadwordEntry Group of lexicalEntries related to a specific result for a given word ID.
type HeadwordEntry struct {
	// The identifier of a word
	Id string `json:"id"`
	// IANA language code
	Language string `json:"language"`
	// A grouping of various senses in a specific language, and a lexical category that relates to a word
	LexicalEntries []LexicalEntry `json:"lexicalEntries"`
	// A list of possible pronunciations of a word
	Pronunciations *[]map[string]interface{} `json:"pronunciations,omitempty"`
	// The json object type. Could be 'headword', 'inflection' or 'phrase'
	Type *string `json:"type,omitempty"`
	// (DEPRECATED) A given written or spoken realisation of an entry, lowercased.
	Word string `json:"word"`
}

// NewHeadwordEntry instantiates a new HeadwordEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeadwordEntry(id string, language string, lexicalEntries []LexicalEntry, word string) *HeadwordEntry {
	this := HeadwordEntry{}
	this.Id = id
	this.Language = language
	this.LexicalEntries = lexicalEntries
	this.Word = word
	return &this
}

// NewHeadwordEntryWithDefaults instantiates a new HeadwordEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeadwordEntryWithDefaults() *HeadwordEntry {
	this := HeadwordEntry{}
	return &this
}

// GetId returns the Id field value
func (o *HeadwordEntry) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HeadwordEntry) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HeadwordEntry) SetId(v string) {
	o.Id = v
}

// GetLanguage returns the Language field value
func (o *HeadwordEntry) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *HeadwordEntry) GetLanguageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *HeadwordEntry) SetLanguage(v string) {
	o.Language = v
}

// GetLexicalEntries returns the LexicalEntries field value
func (o *HeadwordEntry) GetLexicalEntries() []LexicalEntry {
	if o == nil {
		var ret []LexicalEntry
		return ret
	}

	return o.LexicalEntries
}

// GetLexicalEntriesOk returns a tuple with the LexicalEntries field value
// and a boolean to check if the value has been set.
func (o *HeadwordEntry) GetLexicalEntriesOk() (*[]LexicalEntry, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LexicalEntries, true
}

// SetLexicalEntries sets field value
func (o *HeadwordEntry) SetLexicalEntries(v []LexicalEntry) {
	o.LexicalEntries = v
}

// GetPronunciations returns the Pronunciations field value if set, zero value otherwise.
func (o *HeadwordEntry) GetPronunciations() []map[string]interface{} {
	if o == nil || o.Pronunciations == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Pronunciations
}

// GetPronunciationsOk returns a tuple with the Pronunciations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadwordEntry) GetPronunciationsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Pronunciations == nil {
		return nil, false
	}
	return o.Pronunciations, true
}

// HasPronunciations returns a boolean if a field has been set.
func (o *HeadwordEntry) HasPronunciations() bool {
	if o != nil && o.Pronunciations != nil {
		return true
	}

	return false
}

// SetPronunciations gets a reference to the given []map[string]interface{} and assigns it to the Pronunciations field.
func (o *HeadwordEntry) SetPronunciations(v []map[string]interface{}) {
	o.Pronunciations = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *HeadwordEntry) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadwordEntry) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *HeadwordEntry) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *HeadwordEntry) SetType(v string) {
	o.Type = &v
}

// GetWord returns the Word field value
func (o *HeadwordEntry) GetWord() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Word
}

// GetWordOk returns a tuple with the Word field value
// and a boolean to check if the value has been set.
func (o *HeadwordEntry) GetWordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Word, true
}

// SetWord sets field value
func (o *HeadwordEntry) SetWord(v string) {
	o.Word = v
}

func (o HeadwordEntry) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["language"] = o.Language
	}
	if true {
		toSerialize["lexicalEntries"] = o.LexicalEntries
	}
	if o.Pronunciations != nil {
		toSerialize["pronunciations"] = o.Pronunciations
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["word"] = o.Word
	}
	return json.Marshal(toSerialize)
}

type NullableHeadwordEntry struct {
	value *HeadwordEntry
	isSet bool
}

func (v NullableHeadwordEntry) Get() *HeadwordEntry {
	return v.value
}

func (v *NullableHeadwordEntry) Set(val *HeadwordEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableHeadwordEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableHeadwordEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeadwordEntry(val *HeadwordEntry) *NullableHeadwordEntry {
	return &NullableHeadwordEntry{value: val, isSet: true}
}

func (v NullableHeadwordEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeadwordEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


