/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// Languages Schema for the languages endpoint.
type Languages struct {
	// Additional Information provided by OUP
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	// A list of languages available.
	Results *[]LanguagesResults `json:"results,omitempty"`
}

// NewLanguages instantiates a new Languages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLanguages() *Languages {
	this := Languages{}
	return &this
}

// NewLanguagesWithDefaults instantiates a new Languages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLanguagesWithDefaults() *Languages {
	this := Languages{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Languages) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Languages) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Languages) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Languages) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *Languages) GetResults() []LanguagesResults {
	if o == nil || o.Results == nil {
		var ret []LanguagesResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Languages) GetResultsOk() (*[]LanguagesResults, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *Languages) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []LanguagesResults and assigns it to the Results field.
func (o *Languages) SetResults(v []LanguagesResults) {
	o.Results = &v
}

func (o Languages) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableLanguages struct {
	value *Languages
	isSet bool
}

func (v NullableLanguages) Get() *Languages {
	return v.value
}

func (v *NullableLanguages) Set(val *Languages) {
	v.value = val
	v.isSet = true
}

func (v NullableLanguages) IsSet() bool {
	return v.isSet
}

func (v *NullableLanguages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanguages(val *Languages) *NullableLanguages {
	return &NullableLanguages{value: val, isSet: true}
}

func (v NullableLanguages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanguages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


