/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// UtilityLabels Schema for lexicalcategories, registers utility endpoints.
type UtilityLabels struct {
	// Additional Information provided by OUP
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	// Mapping of labels available.
	Results *map[string]UtilityLabelsResults `json:"results,omitempty"`
}

// NewUtilityLabels instantiates a new UtilityLabels object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtilityLabels() *UtilityLabels {
	this := UtilityLabels{}
	return &this
}

// NewUtilityLabelsWithDefaults instantiates a new UtilityLabels object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtilityLabelsWithDefaults() *UtilityLabels {
	this := UtilityLabels{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UtilityLabels) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilityLabels) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UtilityLabels) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UtilityLabels) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *UtilityLabels) GetResults() map[string]UtilityLabelsResults {
	if o == nil || o.Results == nil {
		var ret map[string]UtilityLabelsResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilityLabels) GetResultsOk() (*map[string]UtilityLabelsResults, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *UtilityLabels) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]UtilityLabelsResults and assigns it to the Results field.
func (o *UtilityLabels) SetResults(v map[string]UtilityLabelsResults) {
	o.Results = &v
}

func (o UtilityLabels) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableUtilityLabels struct {
	value *UtilityLabels
	isSet bool
}

func (v NullableUtilityLabels) Get() *UtilityLabels {
	return v.value
}

func (v *NullableUtilityLabels) Set(val *UtilityLabels) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilityLabels) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilityLabels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilityLabels(val *UtilityLabels) *NullableUtilityLabels {
	return &NullableUtilityLabels{value: val, isSet: true}
}

func (v NullableUtilityLabels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilityLabels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


