/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// RegistersList struct for RegistersList
type RegistersList struct {
}

// NewRegistersList instantiates a new RegistersList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistersList() *RegistersList {
	this := RegistersList{}
	return &this
}

// NewRegistersListWithDefaults instantiates a new RegistersList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistersListWithDefaults() *RegistersList {
	this := RegistersList{}
	return &this
}

func (o RegistersList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableRegistersList struct {
	value *RegistersList
	isSet bool
}

func (v NullableRegistersList) Get() *RegistersList {
	return v.value
}

func (v *NullableRegistersList) Set(val *RegistersList) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistersList) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistersList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistersList(val *RegistersList) *NullableRegistersList {
	return &NullableRegistersList{value: val, isSet: true}
}

func (v NullableRegistersList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistersList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


