/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// ThesaurusLink Link to a specific sense of an entry in the thesaurus Dictionary
type ThesaurusLink struct {
	// identifier of a word
	EntryId string `json:"entry_id"`
	// identifier of a sense
	SenseId string `json:"sense_id"`
}

// NewThesaurusLink instantiates a new ThesaurusLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThesaurusLink(entryId string, senseId string) *ThesaurusLink {
	this := ThesaurusLink{}
	this.EntryId = entryId
	this.SenseId = senseId
	return &this
}

// NewThesaurusLinkWithDefaults instantiates a new ThesaurusLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThesaurusLinkWithDefaults() *ThesaurusLink {
	this := ThesaurusLink{}
	return &this
}

// GetEntryId returns the EntryId field value
func (o *ThesaurusLink) GetEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value
// and a boolean to check if the value has been set.
func (o *ThesaurusLink) GetEntryIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EntryId, true
}

// SetEntryId sets field value
func (o *ThesaurusLink) SetEntryId(v string) {
	o.EntryId = v
}

// GetSenseId returns the SenseId field value
func (o *ThesaurusLink) GetSenseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SenseId
}

// GetSenseIdOk returns a tuple with the SenseId field value
// and a boolean to check if the value has been set.
func (o *ThesaurusLink) GetSenseIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SenseId, true
}

// SetSenseId sets field value
func (o *ThesaurusLink) SetSenseId(v string) {
	o.SenseId = v
}

func (o ThesaurusLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["entry_id"] = o.EntryId
	}
	if true {
		toSerialize["sense_id"] = o.SenseId
	}
	return json.Marshal(toSerialize)
}

type NullableThesaurusLink struct {
	value *ThesaurusLink
	isSet bool
}

func (v NullableThesaurusLink) Get() *ThesaurusLink {
	return v.value
}

func (v *NullableThesaurusLink) Set(val *ThesaurusLink) {
	v.value = val
	v.isSet = true
}

func (v NullableThesaurusLink) IsSet() bool {
	return v.isSet
}

func (v *NullableThesaurusLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThesaurusLink(val *ThesaurusLink) *NullableThesaurusLink {
	return &NullableThesaurusLink{value: val, isSet: true}
}

func (v NullableThesaurusLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThesaurusLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


