/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// DomainClassesList struct for DomainClassesList
type DomainClassesList struct {
}

// NewDomainClassesList instantiates a new DomainClassesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainClassesList() *DomainClassesList {
	this := DomainClassesList{}
	return &this
}

// NewDomainClassesListWithDefaults instantiates a new DomainClassesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainClassesListWithDefaults() *DomainClassesList {
	this := DomainClassesList{}
	return &this
}

func (o DomainClassesList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableDomainClassesList struct {
	value *DomainClassesList
	isSet bool
}

func (v NullableDomainClassesList) Get() *DomainClassesList {
	return v.value
}

func (v *NullableDomainClassesList) Set(val *DomainClassesList) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainClassesList) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainClassesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainClassesList(val *DomainClassesList) *NullableDomainClassesList {
	return &NullableDomainClassesList{value: val, isSet: true}
}

func (v NullableDomainClassesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainClassesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


