/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// RegionsList struct for RegionsList
type RegionsList struct {
}

// NewRegionsList instantiates a new RegionsList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionsList() *RegionsList {
	this := RegionsList{}
	return &this
}

// NewRegionsListWithDefaults instantiates a new RegionsList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionsListWithDefaults() *RegionsList {
	this := RegionsList{}
	return &this
}

func (o RegionsList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableRegionsList struct {
	value *RegionsList
	isSet bool
}

func (v NullableRegionsList) Get() *RegionsList {
	return v.value
}

func (v *NullableRegionsList) Set(val *RegionsList) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionsList) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionsList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionsList(val *RegionsList) *NullableRegionsList {
	return &NullableRegionsList{value: val, isSet: true}
}

func (v NullableRegionsList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionsList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


