/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// Inflections Schema for the inflections endpoint.
type Inflections struct {
	// Additional Information provided by OUP
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	// A list of headwords matching a given word
	Results *[]HeadwordInflection `json:"results,omitempty"`
}

// NewInflections instantiates a new Inflections object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInflections() *Inflections {
	this := Inflections{}
	return &this
}

// NewInflectionsWithDefaults instantiates a new Inflections object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInflectionsWithDefaults() *Inflections {
	this := Inflections{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Inflections) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inflections) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Inflections) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Inflections) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *Inflections) GetResults() []HeadwordInflection {
	if o == nil || o.Results == nil {
		var ret []HeadwordInflection
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Inflections) GetResultsOk() (*[]HeadwordInflection, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *Inflections) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []HeadwordInflection and assigns it to the Results field.
func (o *Inflections) SetResults(v []HeadwordInflection) {
	o.Results = &v
}

func (o Inflections) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableInflections struct {
	value *Inflections
	isSet bool
}

func (v NullableInflections) Get() *Inflections {
	return v.value
}

func (v *NullableInflections) Set(val *Inflections) {
	v.value = val
	v.isSet = true
}

func (v NullableInflections) IsSet() bool {
	return v.isSet
}

func (v *NullableInflections) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInflections(val *Inflections) *NullableInflections {
	return &NullableInflections{value: val, isSet: true}
}

func (v NullableInflections) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInflections) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


