/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// ToneGroupTones struct for ToneGroupTones
type ToneGroupTones struct {
	Type string `json:"type"`
	Value string `json:"value"`
}

// NewToneGroupTones instantiates a new ToneGroupTones object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToneGroupTones(type_ string, value string) *ToneGroupTones {
	this := ToneGroupTones{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewToneGroupTonesWithDefaults instantiates a new ToneGroupTones object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToneGroupTonesWithDefaults() *ToneGroupTones {
	this := ToneGroupTones{}
	return &this
}

// GetType returns the Type field value
func (o *ToneGroupTones) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ToneGroupTones) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ToneGroupTones) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *ToneGroupTones) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ToneGroupTones) GetValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ToneGroupTones) SetValue(v string) {
	o.Value = v
}

func (o ToneGroupTones) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableToneGroupTones struct {
	value *ToneGroupTones
	isSet bool
}

func (v NullableToneGroupTones) Get() *ToneGroupTones {
	return v.value
}

func (v *NullableToneGroupTones) Set(val *ToneGroupTones) {
	v.value = val
	v.isSet = true
}

func (v NullableToneGroupTones) IsSet() bool {
	return v.isSet
}

func (v *NullableToneGroupTones) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToneGroupTones(val *ToneGroupTones) *NullableToneGroupTones {
	return &NullableToneGroupTones{value: val, isSet: true}
}

func (v NullableToneGroupTones) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToneGroupTones) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


