/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oxforddictionaries

import (
	"encoding/json"
)

// Thesaurus Schema for thesaurus endpoint
type Thesaurus struct {
	// Additional Information provided by OUP
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	// A list of found synonyms or antonyms
	Results *[]HeadwordThesaurus `json:"results,omitempty"`
}

// NewThesaurus instantiates a new Thesaurus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThesaurus() *Thesaurus {
	this := Thesaurus{}
	return &this
}

// NewThesaurusWithDefaults instantiates a new Thesaurus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThesaurusWithDefaults() *Thesaurus {
	this := Thesaurus{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Thesaurus) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Thesaurus) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Thesaurus) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Thesaurus) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *Thesaurus) GetResults() []HeadwordThesaurus {
	if o == nil || o.Results == nil {
		var ret []HeadwordThesaurus
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Thesaurus) GetResultsOk() (*[]HeadwordThesaurus, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *Thesaurus) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []HeadwordThesaurus and assigns it to the Results field.
func (o *Thesaurus) SetResults(v []HeadwordThesaurus) {
	o.Results = &v
}

func (o Thesaurus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableThesaurus struct {
	value *Thesaurus
	isSet bool
}

func (v NullableThesaurus) Get() *Thesaurus {
	return v.value
}

func (v *NullableThesaurus) Set(val *Thesaurus) {
	v.value = val
	v.isSet = true
}

func (v NullableThesaurus) IsSet() bool {
	return v.isSet
}

func (v *NullableThesaurus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThesaurus(val *Thesaurus) *NullableThesaurus {
	return &NullableThesaurus{value: val, isSet: true}
}

func (v NullableThesaurus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThesaurus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


